//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_history
    {
        public int ID_PHM { get; set; }
        public string PHM { get; set; }
        public string Symtpomatic { get; set; }
        public string Email { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
